[package]
name = "hmc5883l"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal = "0.2.7"
panic-halt = "0.2.0"
fugit = "0.3.7"
cortex-m-rt = "0.7.5"

[dependencies.stm32f1xx-hal]
version = "0.10.0"
features = ["rt", "stm32f103", "medium"]
